# Required
sonar.projectKey=DevSecOpsApp
sonar.projectName=DevSecOps App
sonar.projectVersion=1.0

# Where the source code is
sonar.sources=.

# Language (optional, auto-detect usually)
sonar.language=js

# Exclude node_modules
sonar.exclusions=node_modules/**

# Encoding
sonar.sourceEncoding=UTF-8